import Head from "next/head";

import { useEffect, useState, Fragment } from "react";
import { socket } from "../lib/socket/socket";
import FlowChartProvider from "../components/FlowChartWrapper";

import { api } from "~/@/utils/api";
import SidebarMenu from "../components/SidebarMenu";
import ChartsMenu from "../components/ChartsMenu";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  // const [openSidebar, setOpenSidebar] = useState(true);
  // const [wsConnected, setWsConnected] = useState(socket.connected);

  return (
    <>
      <Head>
        <title>Flowchart T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen justify-center">
        <ChartsMenu />
      </div>

      {/* <SidebarMenu openSidebar={openSidebar} setOpenSidebar={setOpenSidebar} />
      <div className="static h-screen w-screen">
        <button
          type="button"
          onClick={() => setOpenSidebar(true)}
          className="absolute right-3 top-24 z-10 rounded-full bg-indigo-600 px-3 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        >
          Charts
        </button>
        <FlowChartProvider wsConnected={wsConnected} />
      </div> */}
    </>
  );
}
